version: '3.9'

services:
  db1:
    container_name: db1
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata1:/var/lib/postgresql/data
  db2:
    container_name: db2
    image: 'postgres:12'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata1: {}
  pgdata2: {}